server:
  port: 8020
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://115.159.106.212:3306/filmdata?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

endpoints:
  enabled: false
logging:
  file: ./log/FilmData.log
---
spring:
  profiles: dev
  jpa:
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/filmdata?useUnicode=true&characterEncoding=UTF-8
endpoints:
  enabled: true